### ISSUE TITLE
Could be made more smooth in terms of interactivity and speed

### ISSUE THREAD

**Issue by darshjain** [ameybhavsar24/particles#1]

**Comment by ameybhavsar24** [comment]
@darshjain 
Thank you for opening the issue. I have too observed jagged motion in repulsion of particles. If you could find a way to make it smoother like the one the library's [webpage](https://vincentgarreau.com/particles.js/), feel free to open a PR.

**Comment by darshjain** [comment]
Yes i can
https://darshjain.github.io/Particle_JS/
refer to this this is soft enough. 
If this works out for you i can open up a PR for the same
